#!/bin/bash
#======================================================================
# Function: Output the version information of OpenWrt as needed
# Copyright (C) 2021 https://github.com/lasthinker/amlogic-s9xxx-openwrt
#======================================================================

cat ../../etc/openwrt_release
cat ../../etc/flippy-openwrt-release
cat ../../proc/version
